# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60465261fba9ee8e5a3951b6d9cb75628241fe0d988144d905301004597aaa6a70e8a6c95b7e61c036af0719078acf9b512d9672b479eede2c3a22e0668fae08

test:
  secret_key_base: db4271fe6d66e6548ea33bf0a5167e391be27bc7913835edf59f705d6b0313526524255a5dc7781b9ccadc86e8120470b654736620301f44dbcc2b71ce321d05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
